// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Henrik O. Sørensen
// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of
// the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.

using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace Squint.Generator;

/// <summary>
/// Writes one generated C# file: a header, a namespace, one internal static class of tables.
/// </summary>
/// <remarks>
/// Everything is emitted as ASCII. A string table holding combining marks and decomposed
/// sequences would otherwise be at the mercy of any editor that normalises what it saves, and a
/// table of canonical decompositions that has been recomposed is wrong in a way no test on the
/// generator would catch.
/// </remarks>
public sealed class SourceWriter
{
    private const int ValuesPerLine = 12;
    private const int CharsPerLiteral = 96;

    private readonly StringBuilder _text = new StringBuilder();

    /// <summary>
    /// Starts the file: header comment, namespace, class declaration.
    /// </summary>
    public SourceWriter(string className, string summary)
    {
        _text.Append("// <auto-generated/>\n");
        _text.Append("// SPDX-License-Identifier: MPL-2.0\n");
        _text.Append("// Copyright (c) 2026 Henrik O. S\u00F8rensen\n");
        _text.Append("// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of\n");
        _text.Append("// the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.\n");
        _text.Append("// Generated from Unicode data files, which are under the Unicode License v3 (LICENSE.unicode).\n");
        _text.Append("// Written by Squint.Generator from the files under ucd/. Do not edit; regenerate.\n");
        _text.Append("#nullable enable\n");
        _text.Append('\n');
        _text.Append("namespace Squint;\n");
        _text.Append('\n');
        _text.Append("/// <summary>\n");
        _text.Append("/// ").Append(summary).Append('\n');
        _text.Append("/// </summary>\n");
        _text.Append("internal static class ").Append(className).Append('\n');
        _text.Append("{\n");
    }

    /// <summary>
    /// A string constant.
    /// </summary>
    public void Constant(string name, string value)
    {
        _text.Append("    internal const string ").Append(name).Append(" = \"").Append(Escape(value)).Append("\";\n\n");
    }

    /// <summary>
    /// An integer constant.
    /// </summary>
    public void Constant(string name, int value)
    {
        _text.Append("    internal const int ").Append(name).Append(" = ").Append(value.ToString(CultureInfo.InvariantCulture)).Append(";\n\n");
    }

    /// <summary>
    /// An array of code points or packed integers, written in hexadecimal.
    /// </summary>
    public void IntArray(string name, IReadOnlyList<int> values)
    {
        Array("int", name, values.Count, i => "0x" + values[i].ToString("X", CultureInfo.InvariantCulture));
    }

    /// <summary>
    /// An array of small values.
    /// </summary>
    public void ByteArray(string name, IReadOnlyList<byte> values)
    {
        Array("byte", name, values.Count, i => values[i].ToString(CultureInfo.InvariantCulture));
    }

    /// <summary>
    /// An array of table indices or flag sets.
    /// </summary>
    public void UShortArray(string name, IReadOnlyList<ushort> values)
    {
        Array("ushort", name, values.Count, i => values[i].ToString(CultureInfo.InvariantCulture));
    }

    /// <summary>
    /// An array of bit-set words.
    /// </summary>
    public void ULongArray(string name, IReadOnlyList<ulong> values)
    {
        Array("ulong", name, values.Count, i => "0x" + values[i].ToString("X16", CultureInfo.InvariantCulture) + "UL");
    }

    /// <summary>
    /// An array of packed pairs, written in hexadecimal.
    /// </summary>
    public void LongArray(string name, IReadOnlyList<long> values)
    {
        Array("long", name, values.Count, i => "0x" + values[i].ToString("X", CultureInfo.InvariantCulture) + "L");
    }

    /// <summary>
    /// An array of string literals.
    /// </summary>
    public void StringArray(string name, IReadOnlyList<string> values)
    {
        _text.Append("    internal static readonly string[] ").Append(name).Append(" =\n    [\n");

        foreach (string value in values)
        {
            _text.Append("        \"").Append(Escape(value)).Append("\",\n");
        }

        _text.Append("    ];\n\n");
    }

    /// <summary>
    /// One long string, split into concatenated literals the compiler folds back together.
    /// </summary>
    public void StringTable(string name, string value)
    {
        _text.Append("    internal const string ").Append(name).Append(" =\n");

        if (value.Length == 0)
        {
            _text.Append("        \"\";\n\n");
            return;
        }

        for (int offset = 0; offset < value.Length; offset += CharsPerLiteral)
        {
            int length = value.Length - offset;

            if (length > CharsPerLiteral)
            {
                length = CharsPerLiteral;
            }

            _text.Append("        \"").Append(Escape(value.Substring(offset, length))).Append('"');
            _text.Append(offset + length < value.Length ? " +\n" : ";\n\n");
        }
    }

    /// <summary>
    /// Finishes the class and returns the file.
    /// </summary>
    public override string ToString()
    {
        // Drop the blank line the last member left, then close the class.
        string body = _text.ToString().TrimEnd('\n');
        return body + "\n}\n";
    }

    private static string Escape(string value)
    {
        StringBuilder escaped = new StringBuilder(value.Length * 2);

        foreach (char c in value)
        {
            if (c == '"' || c == '\\')
            {
                escaped.Append('\\').Append(c);
            }
            else if (c >= 0x20 && c < 0x7F)
            {
                escaped.Append(c);
            }
            else
            {
                escaped.Append("\\u").Append(((int)c).ToString("X4", CultureInfo.InvariantCulture));
            }
        }

        return escaped.ToString();
    }

    private void Array(string type, string name, int count, System.Func<int, string> format)
    {
        _text.Append("    internal static readonly ").Append(type).Append("[] ").Append(name).Append(" =\n    [\n");

        for (int i = 0; i < count; i++)
        {
            if (i % ValuesPerLine == 0)
            {
                _text.Append("        ");
            }

            _text.Append(format(i)).Append(',');
            _text.Append((i % ValuesPerLine == ValuesPerLine - 1) || i == count - 1 ? "\n" : " ");
        }

        _text.Append("    ];\n\n");
    }
}
