// SPDX-License-Identifier: LGPL-2.1-or-later
// Copyright (c) 2026 Henrik O. Sørensen

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace Squint.Generator;

/// <summary>
/// Turns the files under <c>ucd/</c> into the tables the library binary-searches at runtime.
/// </summary>
/// <remarks>
/// Every table is checked against what the specification promises of the data before it is
/// written: one confusable prototype per code point, decimal digits in runs of ten, and
/// <c>Identifier_Status</c> agreeing with <c>Identifier_Type</c>. A data file that breaks a
/// promise fails generation rather than shipping a table that quietly means something else.
/// </remarks>
public static class TableGenerator
{
    private const int CodePointCount = 0x110000;

    private static readonly char[] Space = { ' ' };

    /// <summary>
    /// The <c>Identifier_Type</c> values, in the bit order <c>Squint.IdentifierType</c> declares.
    /// </summary>
    public static readonly IReadOnlyList<string> IdentifierTypeNames = new[]
    {
        "Not_Character",
        "Deprecated",
        "Default_Ignorable",
        "Not_NFKC",
        "Not_XID",
        "Exclusion",
        "Obsolete",
        "Technical",
        "Uncommon_Use",
        "Limited_Use",
        "Inclusion",
        "Recommended",
    };

    /// <summary>
    /// Generates every file, keyed by file name.
    /// </summary>
    public static IReadOnlyDictionary<string, string> Generate(string ucdDirectory)
    {
        string version = UcdFile.ReadVersion(Path.Combine(ucdDirectory, "confusables.txt"));
        CheckVersion(ucdDirectory, "Scripts.txt", version);
        CheckVersion(ucdDirectory, "ScriptExtensions.txt", version);
        CheckVersion(ucdDirectory, "IdentifierType.txt", version);
        CheckVersion(ucdDirectory, "IdentifierStatus.txt", version);
        CheckVersion(ucdDirectory, "DerivedCoreProperties.txt", version);
        CheckVersion(ucdDirectory, "DerivedNormalizationProps.txt", version);
        CheckVersion(ucdDirectory, "PropertyValueAliases.txt", version);

        ScriptRegistry scripts = ScriptRegistry.Load(Path.Combine(ucdDirectory, "PropertyValueAliases.txt"));
        UnicodeDataFile unicodeData = UnicodeDataFile.Load(Path.Combine(ucdDirectory, "UnicodeData.txt"));

        Dictionary<string, string> files = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["UnicodeScript.g.cs"] = WriteScriptEnum(scripts, version),
            ["ScriptData.g.cs"] = WriteScriptData(ucdDirectory, scripts),
            ["IdentifierData.g.cs"] = WriteIdentifierData(ucdDirectory),
            ["NormalizationData.g.cs"] = WriteNormalizationData(ucdDirectory, unicodeData),
            ["ConfusableData.g.cs"] = WriteConfusableData(ucdDirectory),
            ["CharacterData.g.cs"] = WriteCharacterData(ucdDirectory, unicodeData),
        };

        return files;
    }

    private static void CheckVersion(string ucdDirectory, string file, string expected)
    {
        string actual = UcdFile.ReadVersion(Path.Combine(ucdDirectory, file));

        if (!string.Equals(actual, expected, StringComparison.Ordinal))
        {
            throw new InvalidDataException($"{file} is version {actual}; confusables.txt is {expected}.");
        }
    }

    private static string WriteScriptEnum(ScriptRegistry scripts, string version)
    {
        StringBuilder text = new StringBuilder();
        text.Append("// <auto-generated/>\n");
        text.Append("// SPDX-License-Identifier: LGPL-2.1-or-later\n");
        text.Append("// Copyright (c) 2026 Henrik O. S\u00F8rensen\n");
        text.Append("// Generated from Unicode data files, which are under the Unicode License v3 (LICENSE.unicode).\n");
        text.Append("// Written by Squint.Generator from the files under ucd/. Do not edit; regenerate.\n");
        text.Append("#nullable enable\n");
        text.Append('\n');
        text.Append("namespace Squint;\n");
        text.Append('\n');
        text.Append("/// <summary>\n");
        text.Append("/// A value of the Unicode <c>Script</c> property, plus the three writing systems UTS #39\n");
        text.Append("/// adds for mixed-script detection: <see cref=\"HanWithBopomofo\"/>, <see cref=\"Japanese\"/>\n");
        text.Append("/// and <see cref=\"Korean\"/>.\n");
        text.Append("/// </summary>\n");
        text.Append("/// <remarks>\n");
        text.Append("/// Generated from PropertyValueAliases.txt for Unicode ").Append(version).Append(". The numeric values are\n");
        text.Append("/// positions in a <see cref=\"ScriptSet\"/> and may change between versions of this library;\n");
        text.Append("/// persist <see cref=\"Scripts.Code\"/>, never the number.\n");
        text.Append("/// </remarks>\n");
        text.Append("public enum UnicodeScript\n");
        text.Append("{\n");

        for (int i = 0; i < scripts.Count; i++)
        {
            ScriptInfo script = scripts[i];
            text.Append("    /// <summary>\n");
            text.Append("    /// ").Append(script.Summary).Append('\n');
            text.Append("    /// </summary>\n");
            text.Append("    ").Append(script.EnumName).Append(" = ").Append(i).Append(",\n");

            if (i < scripts.Count - 1)
            {
                text.Append('\n');
            }
        }

        text.Append("}\n");
        return text.ToString();
    }

    private static string WriteScriptData(string ucdDirectory, ScriptRegistry scripts)
    {
        // The Script property: every code point has one, Unknown by default.
        byte[] scriptOf = new byte[CodePointCount];
        byte unknown = (byte)scripts.IndexOf("Zzzz");

        for (int i = 0; i < scriptOf.Length; i++)
        {
            scriptOf[i] = unknown;
        }

        foreach (UcdLine line in UcdFile.Read(Path.Combine(ucdDirectory, "Scripts.txt")))
        {
            byte script = (byte)scripts.IndexOfName(line.Fields[0]);

            for (int cp = line.Start; cp <= line.End; cp++)
            {
                scriptOf[cp] = script;
            }
        }

        // Script_Extensions: only the code points the file lists; the rest default to {Script}.
        // Each distinct set is stored once and referenced by index.
        List<ulong[]> sets = new List<ulong[]>();
        Dictionary<string, int> setIndex = new Dictionary<string, int>(StringComparer.Ordinal);
        List<int> extensionStarts = new List<int>();
        List<int> extensionEnds = new List<int>();
        List<ushort> extensionSets = new List<ushort>();

        List<UcdLine> extensionLines = UcdFile.Read(Path.Combine(ucdDirectory, "ScriptExtensions.txt"))
                                              .OrderBy(l => l.Start)
                                              .ToList();
        int previousEnd = -1;

        foreach (UcdLine line in extensionLines)
        {
            if (line.Start <= previousEnd)
            {
                throw new InvalidDataException($"ScriptExtensions.txt overlaps at {line.Start:X4}.");
            }

            previousEnd = line.End;

            string[] codes = line.Fields[0].Split(Space, StringSplitOptions.RemoveEmptyEntries);
            ulong[] words = new ulong[4];

            foreach (string code in codes)
            {
                int index = scripts.IndexOf(code);
                words[index / 64] |= 1UL << (index % 64);
            }

            string key = string.Join(",", words);

            if (!setIndex.TryGetValue(key, out int setNumber))
            {
                setNumber = sets.Count;
                sets.Add(words);
                setIndex[key] = setNumber;
            }

            extensionStarts.Add(line.Start);
            extensionEnds.Add(line.End);
            extensionSets.Add((ushort)setNumber);
        }

        List<int> runStarts = new List<int>();
        List<byte> runScripts = new List<byte>();
        RunLengthEncode(scriptOf, runStarts, runScripts);

        List<ulong> setWords = new List<ulong>();

        foreach (ulong[] words in sets)
        {
            setWords.AddRange(words);
        }

        List<string> codes4 = new List<string>();
        List<string> names = new List<string>();

        for (int i = 0; i < scripts.Count; i++)
        {
            codes4.Add(scripts[i].Code);
            names.Add(scripts[i].LongName);
        }

        SourceWriter writer = new SourceWriter("ScriptData", "The Script and Script_Extensions properties, from Scripts.txt and ScriptExtensions.txt.");
        writer.Constant("ScriptCount", scripts.Count);
        writer.StringArray("Codes", codes4);
        writer.StringArray("Names", names);
        writer.IntArray("RunStarts", runStarts);
        writer.ByteArray("RunScripts", runScripts);
        writer.IntArray("ExtensionStarts", extensionStarts);
        writer.IntArray("ExtensionEnds", extensionEnds);
        writer.UShortArray("ExtensionSets", extensionSets);
        writer.ULongArray("SetWords", setWords);
        return writer.ToString();
    }

    private static string WriteIdentifierData(string ucdDirectory)
    {
        ushort[] typeOf = new ushort[CodePointCount];
        ushort notCharacter = 1;

        for (int i = 0; i < typeOf.Length; i++)
        {
            typeOf[i] = notCharacter;
        }

        foreach (UcdLine line in UcdFile.Read(Path.Combine(ucdDirectory, "IdentifierType.txt")))
        {
            ushort flags = 0;

            foreach (string name in line.Fields[0].Split(Space, StringSplitOptions.RemoveEmptyEntries))
            {
                int bit = IndexOf(IdentifierTypeNames, name);

                if (bit < 0)
                {
                    throw new InvalidDataException($"Unknown Identifier_Type {name}.");
                }

                flags |= (ushort)(1 << bit);
            }

            for (int cp = line.Start; cp <= line.End; cp++)
            {
                typeOf[cp] = flags;
            }
        }

        bool[] allowed = new bool[CodePointCount];
        List<int> allowedStarts = new List<int>();
        List<int> allowedEnds = new List<int>();

        foreach (UcdLine line in UcdFile.Read(Path.Combine(ucdDirectory, "IdentifierStatus.txt")).OrderBy(l => l.Start))
        {
            if (!string.Equals(line.Fields[0], "Allowed", StringComparison.Ordinal))
            {
                throw new InvalidDataException($"IdentifierStatus.txt lists a status other than Allowed at {line.Start:X4}.");
            }

            allowedStarts.Add(line.Start);
            allowedEnds.Add(line.End);

            for (int cp = line.Start; cp <= line.End; cp++)
            {
                allowed[cp] = true;
            }
        }

        // UTS #39 section 3.1: Allowed is exactly the code points whose only types are Inclusion
        // or Recommended. The status file is what ships; this is the check that it still means that.
        ushort allowedTypes = (ushort)((1 << IndexOf(IdentifierTypeNames, "Inclusion")) | (1 << IndexOf(IdentifierTypeNames, "Recommended")));

        for (int cp = 0; cp < CodePointCount; cp++)
        {
            bool derived = typeOf[cp] != 0 && (typeOf[cp] & ~allowedTypes) == 0;

            if (derived != allowed[cp])
            {
                throw new InvalidDataException($"Identifier_Status and Identifier_Type disagree at {cp:X4}.");
            }
        }

        List<int> typeStarts = new List<int>();
        List<ushort> typeValues = new List<ushort>();
        RunLengthEncode(typeOf, typeStarts, typeValues);

        SourceWriter writer = new SourceWriter("IdentifierData", "The Identifier_Type and Identifier_Status properties, from IdentifierType.txt and IdentifierStatus.txt.");
        writer.IntArray("TypeRunStarts", typeStarts);
        writer.UShortArray("TypeRunValues", typeValues);
        writer.IntArray("AllowedStarts", allowedStarts);
        writer.IntArray("AllowedEnds", allowedEnds);
        return writer.ToString();
    }

    private static string WriteNormalizationData(string ucdDirectory, UnicodeDataFile unicodeData)
    {
        // Full canonical decompositions, so the runtime never recurses. Hangul syllables are
        // algorithmic and are not in the table.
        List<int> keys = new List<int>();
        List<int> values = new List<int>();
        StringBuilder blob = new StringBuilder();

        foreach (int cp in unicodeData.CanonicalDecompositions.Keys.OrderBy(k => k))
        {
            StringBuilder full = new StringBuilder();
            AppendFullDecomposition(unicodeData, cp, false, full);

            if (full.Length > 15)
            {
                throw new InvalidDataException($"Decomposition of {cp:X4} is longer than the packing allows.");
            }

            keys.Add(cp);
            values.Add((blob.Length << 4) | full.Length);
            blob.Append(full);
        }

        // Full compatibility decompositions, only where they differ from the canonical one: a
        // code point with a compatibility mapping, or whose canonical mapping reaches one.
        List<int> compatibilityKeys = new List<int>();
        List<int> compatibilityValues = new List<int>();
        StringBuilder compatibilityBlob = new StringBuilder();
        IEnumerable<int> decomposable = unicodeData.CanonicalDecompositions.Keys.Concat(unicodeData.CompatibilityDecompositions.Keys).Distinct().OrderBy(k => k);

        foreach (int cp in decomposable)
        {
            StringBuilder canonical = new StringBuilder();
            AppendFullDecomposition(unicodeData, cp, false, canonical);
            StringBuilder compatibility = new StringBuilder();
            AppendFullDecomposition(unicodeData, cp, true, compatibility);

            if (string.Equals(canonical.ToString(), compatibility.ToString(), StringComparison.Ordinal))
            {
                continue;
            }

            if (compatibility.Length > 63)
            {
                throw new InvalidDataException($"Compatibility decomposition of {cp:X4} is longer than the packing allows.");
            }

            compatibilityKeys.Add(cp);
            compatibilityValues.Add((compatibilityBlob.Length << 6) | compatibility.Length);
            compatibilityBlob.Append(compatibility);
        }

        // Canonical composition: every primary composite, keyed by its pair. A composite is the
        // code point whose one-level canonical decomposition is a pair, unless it carries
        // Full_Composition_Exclusion, which folds in the exclusion list, the singletons and the
        // non-starter decompositions (UAX #15, section 3).
        HashSet<int> excluded = new HashSet<int>();

        foreach (UcdLine line in UcdFile.Read(Path.Combine(ucdDirectory, "DerivedNormalizationProps.txt")))
        {
            if (!string.Equals(line.Fields[0], "Full_Composition_Exclusion", StringComparison.Ordinal))
            {
                continue;
            }

            for (int cp = line.Start; cp <= line.End; cp++)
            {
                excluded.Add(cp);
            }
        }

        SortedDictionary<long, int> pairs = new SortedDictionary<long, int>();

        foreach (KeyValuePair<int, int[]> entry in unicodeData.CanonicalDecompositions)
        {
            if (entry.Value.Length != 2 || excluded.Contains(entry.Key))
            {
                continue;
            }

            long pair = ((long)entry.Value[0] << 21) | (uint)entry.Value[1];

            if (pairs.ContainsKey(pair))
            {
                throw new InvalidDataException($"Two composites for the pair {entry.Value[0]:X4} {entry.Value[1]:X4}.");
            }

            pairs[pair] = entry.Key;
        }

        byte[] classOf = new byte[CodePointCount];

        foreach (KeyValuePair<int, byte> entry in unicodeData.CombiningClasses)
        {
            classOf[entry.Key] = entry.Value;
        }

        List<int> classStarts = new List<int>();
        List<byte> classValues = new List<byte>();
        RunLengthEncode(classOf, classStarts, classValues);

        SourceWriter writer = new SourceWriter("NormalizationData", "Full canonical and compatibility decompositions, canonical combining classes, and the composition pairs, from UnicodeData.txt and DerivedNormalizationProps.txt.");
        writer.IntArray("DecompositionKeys", keys);
        writer.IntArray("DecompositionValues", values);
        writer.StringTable("Decompositions", blob.ToString());
        writer.IntArray("CompatibilityKeys", compatibilityKeys);
        writer.IntArray("CompatibilityValues", compatibilityValues);
        writer.StringTable("CompatibilityDecompositions", compatibilityBlob.ToString());
        writer.LongArray("PairKeys", pairs.Keys.ToList());
        writer.IntArray("PairComposites", pairs.Values.ToList());
        writer.IntArray("CombiningClassStarts", classStarts);
        writer.ByteArray("CombiningClassValues", classValues);
        return writer.ToString();
    }

    private static void AppendFullDecomposition(UnicodeDataFile unicodeData, int cp, bool compatibility, StringBuilder output)
    {
        int[]? mapping;

        if (compatibility && unicodeData.CompatibilityDecompositions.TryGetValue(cp, out mapping))
        {
            foreach (int part in mapping)
            {
                AppendFullDecomposition(unicodeData, part, true, output);
            }
        }
        else if (unicodeData.CanonicalDecompositions.TryGetValue(cp, out mapping))
        {
            foreach (int part in mapping)
            {
                AppendFullDecomposition(unicodeData, part, compatibility, output);
            }
        }
        else
        {
            output.Append(char.ConvertFromUtf32(cp));
        }
    }

    private static string WriteConfusableData(string ucdDirectory)
    {
        SortedDictionary<int, string> prototypes = new SortedDictionary<int, string>();

        foreach (UcdLine line in UcdFile.Read(Path.Combine(ucdDirectory, "confusables.txt")))
        {
            if (line.Start != line.End)
            {
                throw new InvalidDataException($"confusables.txt has a range at {line.Start:X4}.");
            }

            if (prototypes.ContainsKey(line.Start))
            {
                throw new InvalidDataException($"confusables.txt maps {line.Start:X4} twice.");
            }

            StringBuilder target = new StringBuilder();

            foreach (int cp in UcdFile.ParseHexList(line.Fields[0]))
            {
                target.Append(char.ConvertFromUtf32(cp));
            }

            if (target.Length > 255)
            {
                throw new InvalidDataException($"Prototype of {line.Start:X4} is longer than the packing allows.");
            }

            prototypes[line.Start] = target.ToString();
        }

        List<int> keys = new List<int>();
        List<int> values = new List<int>();
        StringBuilder blob = new StringBuilder();

        foreach (KeyValuePair<int, string> entry in prototypes)
        {
            keys.Add(entry.Key);
            values.Add((blob.Length << 8) | entry.Value.Length);
            blob.Append(entry.Value);
        }

        SourceWriter writer = new SourceWriter("ConfusableData", "The confusable prototypes, from confusables.txt.");
        writer.IntArray("Keys", keys);
        writer.IntArray("Values", values);
        writer.StringTable("Targets", blob.ToString());
        return writer.ToString();
    }

    private static string WriteCharacterData(string ucdDirectory, UnicodeDataFile unicodeData)
    {
        List<int> ignorableStarts = new List<int>();
        List<int> ignorableEnds = new List<int>();

        foreach (UcdLine line in UcdFile.Read(Path.Combine(ucdDirectory, "DerivedCoreProperties.txt")).OrderBy(l => l.Start))
        {
            if (!string.Equals(line.Fields[0], "Default_Ignorable_Code_Point", StringComparison.Ordinal))
            {
                continue;
            }

            ignorableStarts.Add(line.Start);
            ignorableEnds.Add(line.End);
        }

        // UTS #39 section 5.3 relies on a decimal digit's zero being the digit minus its value,
        // which holds because every Nd digit sits in a contiguous run of ten. Checked here.
        SortedDictionary<int, int> digitsByZero = new SortedDictionary<int, int>();

        foreach (KeyValuePair<int, int> digit in unicodeData.DecimalDigits)
        {
            int zero = digit.Key - digit.Value;
            digitsByZero.TryGetValue(zero, out int count);
            digitsByZero[zero] = count + 1;
        }

        foreach (KeyValuePair<int, int> run in digitsByZero)
        {
            if (run.Value != 10)
            {
                throw new InvalidDataException($"Decimal digits from zero {run.Key:X4} are not a run of ten.");
            }

            for (int value = 0; value < 10; value++)
            {
                if (!unicodeData.DecimalDigits.TryGetValue(run.Key + value, out int actual) || actual != value)
                {
                    throw new InvalidDataException($"Decimal digit {run.Key + value:X4} is not digit {value}.");
                }
            }
        }

        SourceWriter writer = new SourceWriter("CharacterData", "Default_Ignorable_Code_Point from DerivedCoreProperties.txt, and the zero of every decimal digit run from UnicodeData.txt.");
        writer.Constant("UnicodeVersion", UcdFile.ReadVersion(Path.Combine(ucdDirectory, "confusables.txt")));
        writer.IntArray("DefaultIgnorableStarts", ignorableStarts);
        writer.IntArray("DefaultIgnorableEnds", ignorableEnds);
        writer.IntArray("DigitZeros", digitsByZero.Keys.ToList());
        return writer.ToString();
    }

    private static void RunLengthEncode<T>(T[] values, List<int> starts, List<T> runValues)
        where T : struct, IEquatable<T>
    {
        for (int cp = 0; cp < values.Length; cp++)
        {
            if (cp == 0 || !values[cp].Equals(values[cp - 1]))
            {
                starts.Add(cp);
                runValues.Add(values[cp]);
            }
        }
    }

    private static int IndexOf(IReadOnlyList<string> names, string name)
    {
        for (int i = 0; i < names.Count; i++)
        {
            if (string.Equals(names[i], name, StringComparison.Ordinal))
            {
                return i;
            }
        }

        return -1;
    }
}
